### ISSUE TITLE
Decide on a method to control a series of LEDs

### ISSUE THREAD

**Issue by jamesmack** [Kilonibble/translink-map#1]
Using a series of 74HC164s would be doable, and has been done for a lot of LED projects in the past. It is tedious, however.

Alternatively, we might want to look at the WS2803, which is able to drive 18 LEDs per IC ($16 for 10 DIPs or SOPs from AliExpress):
http://thomasolson.com/PROJECTS/WS2803_Testing/

If we used the WS2803, we could probably adapt this code for it:
https://www.npmjs.com/package/rpi-ws2801

**Comment by rsingla92** [comment]
I like the WS2803 over the 74HC164s. 

18 LEDs per IC is also pretty hard to beat!
