### ISSUE TITLE
Investigate Translink API

### ISSUE THREAD

**Issue by rsingla92** [Kilonibble/translink-map#3]
Obviously a key part of this is getting bus information for select buses we choose to follow (ideally this selection is variable) - we should first understand what the API lets us do.

**Comment by jamesmack** [comment]
https://developer.translink.ca/ServicesRtti/ApiReference

* Stops (returns stops in radius of lat/long)
* Stop Estimates (returns next bus estimate for a given stop ID)
* Buses (returns vehicle location and state info based on bus ID, stop ID, or route ID)
* Routes (returns route information, including a route map, for a given route ID)
* Status (API status)

**Comment by jamesmack** [comment]
Also, from: https://developer.translink.ca/ServicesRtti

"The API will have a restriction of 100/requests per minute per IP and a maximum of around 10000 request/day"

Considering that, we can have just over 400 requests/hour. We'll have to limit update frequency accordingly.

**Comment by rsingla92** [comment]
For a single bus, I'd envision 1 request / minute to be too high (60 requests / hour) for usefulness (resulting in too much power).

Let's say 1 request / 3 minutes would be okay (20 req / hr )...

5 or 10 buses then becomes 100 req / hr or 200 req / hr.

Of course, we could keep this variable depending on the number buses selected. Keep track of the number of requests made thus far and cap the frequency based on the available requests.
